apiVersion: v1
kind: Service
metadata:
  name: job-portal-backend-service
  namespace: default
  labels:
    app: job-portal-backend
    tier: backend
    module: m7-kubernetes
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: job-portal-backend
---
apiVersion: v1
kind: Service
metadata:
  name: job-portal-frontend-service
  namespace: default
  labels:
    app: job-portal-frontend
    tier: frontend
    module: m7-kubernetes
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: job-portal-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: job-portal-service
  namespace: default
  labels:
    app: job-portal
    module: m7-kubernetes
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http-frontend
    - port: 3000
      targetPort: 3000
      name: http-backend
  selector:
    app: job-portal-backend
